// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkhrvapbjwtwumbestjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raHJ2YXBiand0d3VtYmVzdGpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1MDU4NDQsImV4cCI6MjA4OTA4MTg0NH0.zM3fNQqTbmkMU01aqMJ2iO49Z2rDHGGh7DsNu0NLENc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});